name: hello_world
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  faker: ^2.2.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assests/images/goku.png
      - assests/images/GokuSaltando.png
      - assests/emojis/angry.svg
      - assests/emojis/heart.svg
      - assests/emojis/laughing.svg
      - assests/emojis/like.svg
      - assests/emojis/sad.svg
      - assests/emojis/shocked.svg
      - assests/wallpapers/1.jpeg
      - assests/wallpapers/2.jpeg
      - assests/wallpapers/3.jpeg
      - assests/wallpapers/4.jpeg
      - assests/wallpapers/5.jpeg
      - assests/wallpapers/6.jpeg
      - assests/publications/ferrari.jpeg
      - assests/publications/flutter.jpeg
      - assests/logos/facebook.svg
      - assests/users/1.jpg
      - assests/users/2.jpg
      - assests/users/3.jpg
      - assests/users/4.jpg
      - assests/users/5.jpg
      - assests/users/6.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: 
    - family: CustomsIcons
      fonts:
      - asset: assests/icons/CustomIcons.ttf
    - family: Nunito
      fonts:
        - asset: assests/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assests/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assests/fonts/nunito/Nunito-BlackItalic.ttf
          style: italic
        - asset: assests/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assests/fonts/nunito/Nunito-Italic.ttf
          weight: 300
          style: italic
        - asset: assests/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assests/fonts/nunito/Nunito-BlackItalic.ttf
        - weight: 900
          style: italic
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
